version: "2.2"
services:

  backdevopsimage:
    image: "nassimbenali/backdevopsimage:1.0"
    build: ./
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
    depends_on:
      - mysql
    volumes:
      - .m2:/root/.m2


  mysql:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devops
    ports:
      - "3307:3306"